print('Hello, World!')
print('Ameer')
print('Ameer Hamza')
print(1, 2, 3)
print('Hello\nWorld')
print('Hello\tWorld')
print('apple', 'banana', 'cherry', sep=', ')
print(1, 2, 3, sep='-')
print('Hello', end=' ')
print('World')
print(1, end='')
print(2)
print('He said, "Hello!"')
print('This is a backslash: \\')
age = 25
print(f'I am {age} years old')
number = 180
print(f'The number is {number}')
print(1)
print(2)
print(3)
print(4)
print(5)
